### ISSUE TITLE
Removing package error

### ISSUE THREAD

**Issue by Scooletz** [FubuMvcArchive/ripple#103]
Correct me if I'm wrong but as far as I can get, the _RemoveCommand_ does throw on removing package. As I checked, during a package explosion, the package directory (or one of its subdirectories) is marked as ReadOnly, which causes the _FileSystem.DeleteDirectory_ to throw _IOException : Directory is not empty_ which is described in a comment up here http://stackoverflow.com/questions/329355/cannot-delete-directory-with-directory-deletepath-true.
Should _FileSystem_ be modified to remove ReadOnly before a directory removal? Should the _IFileSystem_ provide an explicit _SetAttributes_ method?

I haven't provided the integration test yet, as it would need exploding to disc. Are there any examples in the tests when the _FileSystem_ is used behind to fully go through scenario?

Waiting for your opinions, thoughts.

**Comment by jmarnold** [comment]
I think there's a cleaner syntax for this (File.SetAttributes, if I recall correctly) but I had to do this when we were writing the first iteration of "fubu new":

https://github.com/DarthFubuMVC/fubu/blob/master/src/Fubu/Templating/Steps/DirectoryExtensions.cs

Maybe that could help here?

**Comment by jmarnold** [comment]
You could do the inverse of that during the setup of an integration test.
