### ISSUE TITLE
Optimize the Install command

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/ripple#104]
The install command is slow because of all the connections it makes.  Let's make it try to work completely locally first instead of trying to make remote queries

**Comment by jmarnold** [comment]
If we do that, you're going to absolutely need to specify the desired version in the install command so we can know whether we have authoritative info locally.

**Comment by jeremydmiller** [comment]
No we don't, if it's already installed to the solution, use that version regardless

**Comment by jmarnold** [comment]
Oh. I thought you meant local like the local cache.

**Comment by jeremydmiller** [comment]
Wouldn't mind a flag to do it all locally, but that's a step 2 to me
