### ISSUE TITLE
Transitive references

### ISSUE THREAD

**Issue by Scooletz** [FubuMvcArchive/ripple#108]
What's behind adding transitive references to the projects during fixing references? It does not hurt, as it makes implicit things explicit. What was the idea?

**Comment by jmarnold** [comment]
I'll catch up on ripple stuff as soon as I can. Work tasks got more
involved than I anticipated and I got sick so I'm trying to play catch up.

**Comment by Scooletz** [comment]
Ok Josh. I just did rebase all the pull requests to match master HEAD. They're ready to be pulled :+1:

**Comment by jmarnold** [comment]
I don't think I understand the question. Can you give me an example?

**Comment by Scooletz** [comment]
I'll make a branch with an appropriate test to make it clear.
