### ISSUE TITLE
Install command incorrectly marks recursive dependencies as "Float"

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/ripple#111]
Install FubuMVC.Katana, which depends on OWIN.Types 0.6.4.  OWIN.Types gets added as a "Float", then ripple puts in a newer version of Owin.Types and through the joy of strong naming, nothing works.

I say that if a recursive dependency is NOT part of a floating feed, it's marked as Fixed by default.

**Comment by jmarnold** [comment]
+1

**Comment by jmarnold** [comment]
We can fix ripple for this scenario but we're going to have to get better at keeping up with our nuspecs. That's the primary problem here.
