### ISSUE TITLE
Querying nugets with ripple

### ISSUE THREAD

**Issue by Scooletz** [FubuMvcArchive/ripple#114]
How about providing querying ability to ripple? One could write start few letters of the package and it would print a list of matches with feeds included?
How do you refer to a package when you don't know the full name? Do you use a browser?

**Comment by jmarnold** [comment]
I usually search on nuget.org when I don't know the name of it. Though, the querying wouldn't be too hard to pull off with a find command, maybe?

> ripple find abc

Could list them out:

> ID, Version (Feed)

**Comment by Scooletz** [comment]
:+1: 
Await the pull request.
