### ISSUE TITLE
"Batched" install command

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/ripple#116]
Mostly wanting this to support the new "fubu new" templating story.

Let's say that in the course of running "ripple restore" on a code repository we see a file in the root named "ripple-install.txt" with a format like:

[nuget name]/version:project1, project2, project3
[nuget name]:project1, project2, project3

Have ripple do installs on each.  If there's a version, it's a float.  If there's no version, add to ripple config in the project.  Run the "Fix" command instead.

How does this sound?  I'm trying to make the templating come through ripple's front door

**Comment by jmarnold** [comment]
That could work. Is there any value in trying it with the Fix command first?

**Comment by jeremydmiller** [comment]
There absolutely is, but I was wanting it to be relatively transparent to a user of "fubu new".  Do your fubu new scaffolding, then run rake and you're good to go

**Comment by jeremydmiller** [comment]
I really don't want any logic in FubuCsProjFile or fubu.exe that read and write to the ripple.config file is part of this.  Not so much worried about ripple.dependencies.config

**Comment by jmarnold** [comment]
Gotcha. That would be pretty simple to do. The NugetOperation step just uses an INugetOperationContext to define the operations to perform:

// Context
https://github.com/DarthFubuMVC/ripple/blob/master/src/ripple/Commands/FixCommand.cs#L17

// Usage
https://github.com/DarthFubuMVC/ripple/blob/master/src/ripple/Commands/FixCommand.cs#L34

An input that could read from the "ripple-install.txt" file could slip in pretty easily.

**Comment by jeremydmiller** [comment]
I see it.  Nice.  I'll take that today or tomorrow.

**Comment by jmarnold** [comment]
Unless you're dying to do this, I feel like coding some ripple tonight so I can take this.

**Comment by jeremydmiller** [comment]
Go, go, go!

Just tell me what the format and filename you settle on is.  You're going to have it delete the file on success?

I was thinking:

[Nuget]:project, project, project

or 

[Nuget]/[Version]: project, project, project

But honestly, maybe:

[Project]: Nuget/Version, Nuget, nuget, nuget

is better 'cause I think you'd get more usage out of that by hand.
