### ISSUE TITLE
New batch-install command missed adding references

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/ripple#121]
Installed the nugets, exploded them, added to ripple.dependencies.config, but failed to add the project references.  A simple ripple fix solved the issue.

EDIT:  Only added the nuget to one of the ripple.dep.config files.  Will have to try that one again later.

**Comment by jmarnold** [comment]
Closed via d5d6f6d550540cf163c400a7ce3bab218428abb0
