### ISSUE TITLE
How do you publish tags?

### ISSUE THREAD

**Issue by Scooletz** [FubuMvcArchive/ripple#126]
How do you publish tags? With TeamCity? If so, what did you use to configure it? Some custom script?

**Comment by jeremydmiller** [comment]
We use TeamCity for all our tagging.  Just look under the VCS root tab in the project settings to set permissions, then under each build you'll need to enable tagging.  It takes a couple steps.

Even CC.Net circa 2004 could do that without custom scripts!

**Comment by Scooletz** [comment]
I got VCS Labeling disabled and cannot set it. I think I'll ask on some TeamCity forum or StackOverflow. Thank you for pointing the direction.
