### ISSUE TITLE
Batch-install is NOT respecting the fixed version of nuget when specified

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/ripple#128]
Might be because I was running completely disconnected.  Specified exactly structuremap 2.6.3, but calling ripple restore with the presence of the batch-install.txt file ends up looking for the latest StructureMap in the local  cache instead and off we go to strong named hell

**Comment by jeremydmiller** [comment]
Bit me again tonight.  This time it's a dependency on something else.  Pulling down FubuTestingSupport should give me _exactly_ the right version of NUnit.  Instead, I go the latest.  Breaking fubu new.

**Comment by jmarnold** [comment]
Don't know if I'm going to get to it tonight but this will be fixed by tomorrow.

**Comment by jeremydmiller** [comment]
We had to roll back the fix because it was causing too many problems.  And this is still blocking the "fubu new" work.
