### ISSUE TITLE
Support feed authentication

### ISSUE THREAD

**Issue by yvesgoeleven** [FubuMvcArchive/ripple#156]
One of my feeds requires authentication but I don't see a way to specify credentials at the feed level.

**Comment by jeremydmiller** [comment]
Uh, that's because we haven't needed to do that yet.  What authentication needs to you have?  Just UID/PWD, or something else?

**Comment by yvesgoeleven** [comment]
I'm using a private feed from myget.org, which requires username/password indeed.
