### ISSUE TITLE
Ripple does not recognize a nuget with multiple nupkg files

### ISSUE THREAD

**Issue by NeerajR-** [FubuMvcArchive/ripple#160]
Related to point 3 on:

https://groups.google.com/forum/#!topic/ripple-dev/mVC9HdMeZFM

Fails to init/update where package contains two nupkg files e.g. valueinjector

**Comment by jmarnold** [comment]
I'm looking at the contents of their nupkg and I'm calling foul on them. It's definitely not the norm so I'd rather not change the mechanics of the LocalDependencies class to cater to it.
