### ISSUE TITLE
Allow for explicit references

### ISSUE THREAD

**Issue by CoreyKaylor** [FubuMvcArchive/ripple#166]
The latest nuspec allows you to specify specific references to include. Possibly do something in ripple's config to account for this as well if the package owner doesn't, but you want to keep control?

**Comment by jmarnold** [comment]
Ah, for the assemblies that are bundled in the nuget?

**Comment by CoreyKaylor** [comment]
Yep, say use NUnit as an example. Most of the time you only care to reference nunit.framework.dll.

**Comment by CoreyKaylor** [comment]
Was there a commit somewhere for this?

**Comment by jmarnold** [comment]
Wow, I suck at giving an audit trail. Apparently I snuck this one in over here:
https://github.com/DarthFubuMVC/ripple/commit/cec179f742fee3df972b08df116fbd0dbfcc40a7

It's manually tested. I'm not sure why I didn't just make a commit and associate the message. My bad.

**Comment by CoreyKaylor** [comment]
No sweat, just wasn't sure why it got closed. Thanks :)
