### ISSUE TITLE
Ditch the XML in the ripple.config in favor of object blocks

### ISSUE THREAD

**Issue by jmarnold** [FubuMvcArchive/ripple#175]

**Comment by SimonCropp** [comment]
"object blocks"?

**Comment by jeremydmiller** [comment]
See https://github.com/DarthFubuMVC/fubuobjectblocks

Nobody likes the xml format, and object blocks would give us a _lot_ more flexibility with what we can do.  Plus the case sensitivity of the xml serialization burned us pretty badly today at work.

**Comment by SimonCropp** [comment]
in that case +1
