### ISSUE TITLE
Have a story/doco for xxx.ps1

### ISSUE THREAD

**Issue by SimonCropp** [FubuMvcArchive/ripple#180]
So nuget supports `Init.ps1` `Install.ps1` `Uninstall.ps1`.

This obviously wont work since ripple runs outside the context of VS

So it would be good if this was documented.

Also as a helper it would be good if the console wrote a warning when it detects any of those scripts that wont be run

**Comment by jmarnold** [comment]
Can you elaborate on this? Are you talking about the directive processing maybe?

**Comment by SimonCropp** [comment]
have a look on this page http://docs.nuget.org/docs/creating-packages/creating-and-publishing-a-package for "Automatically Running PowerShell Scripts During Package Installation and Removal"
