### ISSUE TITLE
Ripple 2.3 fails in update with 500's, but 2.2 does not

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/ripple#186]
Seeing this consistently, trying to update FubuTransportation with:

ripple update -n FubuTransportation w/ 2.3 fails with network errors, but downgrading to 2.2 does work -- but differently

**Comment by jmarnold** [comment]
Can you grab the response in Fiddler for me? I wasn't able to reproduce that.

**Comment by jeremydmiller** [comment]
Will do.

**Comment by jmarnold** [comment]
Can you make sure you try this with the very latest? Maybe we do something to isolate network errors an retry depending on where it happens
