### ISSUE TITLE
ripple update -n [NUGET] does not work in 2.3

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/ripple#190]
Using a build from just a day or two ago, unable to get ripple update -n [nuget] to work.  I'll investigate later this morning.

**Comment by jeremydmiller** [comment]
Take a bit of that back.  Looks like it was a web connection failure, but there is no indication in the console output that that's happening.  Maybe "update" needs to fail if all the feeds are not online?

**Comment by jeremydmiller** [comment]
Reverted back to a build of 2.1 and it works.  Something changed in Nuget.Core maybe?

**Comment by jmarnold** [comment]
Should probably make the error gathering smarter. I think what happened was:
- Ripple did a check to see if it was online. It passed
- Somewhere during the update process, your connection failed
- It errored out because it couldn't find what it was looking for

**Comment by jeremydmiller** [comment]
Nevermind, just never mind, nothing to see here.  Except the comment about the update failing if the connectivity isn't there.  Still thinking we have a problem w/ the new Nuget.Core.

**Comment by jmarnold** [comment]
The finding mechanics is using the TPL now. It's more than possible that
I'm missing a fault case in there somewhere.
