### ISSUE TITLE
Support cross project nuget dependencies within the same solution

### ISSUE THREAD

**Issue by andreasohlund** [FubuMvcArchive/ripple#194]
We have a situation where we have a project dependency at build time but when we generate the nugets we are creating separate packages. 

So we have the dependency in ripple.dependencies.config (eg "NServiceBus") so that ripple will generate the deps in the nuspec correctly.

But we don't have it in ripple.config since this solution is generating the "NServiceBus" nuget as well as the others (eg. NServiceBus.AutoFac).

In this scenario a ripple restore will fail with:

```
==========================================
Missing Nugets: Could not find nugets
==========================================
     ** Nugets
        * NServiceBus                Float
        * NServiceBus.Interfaces     Float

18 Sep 2013 22:02:34: [Error] Could not restore dependencies
18 Sep 2013 22:02:34: [Error] ripple.RippleFatalError: Could not restore dependencies
18 Sep 2013 22:02:34: [Error] Error executing DownloadMissingNugets
18 Sep 2013 22:02:34: [Error] ripple.RippleFatalError: Could not restore dependencies
   at ripple.RippleAssert.Fail(String message, Object[] substitutions) in c:\Code\ripple\src\ripple\RippleAssert.cs:line 16
   at ripple.Steps.DownloadMissingNugets.Execute(RippleInput input, IRippleStepRunner runner) in c:\Code\ripple\src\ripple\Steps\DownloadMissingNugets.cs:line 49
   at ripple.RippleOperation.Execute(Boolean throwOnFailure) in c:\Code\ripple\src\ripple\RippleOperation.cs:line 77

```

So in essence this scenario means 1 solution generates more than 1 nuget

How about a "-project" switch to the line in ripple.dependencies.config that tells ripple that this dep is a visual studio project dependency so ripple can safely ignore it?

That way the nuget generation can use that info to make the required updates to the nuspec?

Our current workaround is to add dummy lines to ripple.config to avoid the error

https://github.com/Particular/NServiceBus/commit/4037e495b2fc8c1931ef0be5f43784f5064d1d90

This means a unneeded download and also that a ripple fix will screw up the .csprojs

**Comment by jmarnold** [comment]
Does the project reference analysis not handle this one? I had originally intended for the nuspec generation to be smart enough for a situation like:

ProjectA publishes NugetA
ProjectB publishes NugetB

ProjectB references ProjectA
ProjectB's nuspec depeneds on NugetA

**Comment by SimonCropp** [comment]
a case of "you are using it wrong" see https://github.com/DarthFubuMVC/ripple/issues/199
