### ISSUE TITLE
Should throw an error if a dependency is defined in ripple.dependencies.config and as a Nuspec in ripple.config

### ISSUE THREAD

**Issue by SimonCropp** [FubuMvcArchive/ripple#199]
Dependencies can be defined in `ripple.dependencies.config`. However they can also be derived from project references and `nuspec` nodes in `ripple.config` if nuget in question is create by this solution

However if someone defines a dependency in `ripple.dependencies.config` that is also a project reference ripple will still try to derive and download that nuget. 

If someone puts a dependency in `ripple.dependencies.config` that exists as a `Nuspec` in `ripple.config` it should error.

**Comment by jmarnold** [comment]
Some simple messaging like: "A solution cannot depend on a Nuget that it publishes"

**Comment by SimonCropp** [comment]
> ProjectX has a reference to ProjectY. ProjectX also has a dependency on the nuget produced by ProjectY (PATH_TO_PROJECTX_ripple.dependencies.config). A solution cannot depend on a Nuget that it publishes. To resolve this issue remove the ProjectY dependency from ripple.dependencies.config.
