### ISSUE TITLE
ripple.config keeps on changing

### ISSUE THREAD

**Issue by johnsimons** [FubuMvcArchive/ripple#202]
Not sure if this happens only to us or everyone else.
And also not sure why it happens!

Every so often the ripple.config namespaces decide to change order for no apparent reason, see https://github.com/Particular/NServiceBus/pull/1568/files#diff-1

Before:
`<ripple xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">`
after:
`<ripple xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">`

**Comment by jmarnold** [comment]
I HATE this so much. Going away when we move to object blocks.

**Comment by SimonCropp** [comment]
Or perhaps toml? https://github.com/mojombo/toml

**Comment by jmarnold** [comment]
@Simon

We wanted something more succinct for our configuration story in the Fubu
world so object blocks have already been worked on quite a bit. Originally
did it for ripple but it's proved to be useful in lots of other ways as
well (like our settings pattern).

More importantly, the implementation of the parser goes to an intermediate
object model that then goes through our very powerful model binding
subsystem. That gives us maximum flexibility for the object structures and
cleans things up a LOT.

**Comment by ghost** [comment]
Eh what?

**Comment by jeremydmiller** [comment]
@simon,

Not sure if this is what you were wondering about, but Josh was talking about this:  https://github.com/DarthFubuMVC/fubuobjectblocks

**Comment by ghost** [comment]
Jeremy, are you sure you are referencing the correct Simon? You see, my username is @simon. So every time you write that in a comment, commit, etc I get a notification. I think you we're supposed so reference @simoncropp and not me, @simon.

**Comment by jmarnold** [comment]
Oh, crap!. Sorry, @simon!

**Comment by SimonCropp** [comment]
@simon @jmarnold :)
