### ISSUE TITLE
Ripple should not have to change ripple.config for floating dependencies

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/ripple#216]
One of the big goals of ripple was to prevent the merge hell we experienced with Nuget OOTB.  Having ripple update change versions in the ripple.config file for updates is going to bring that problem right back.

**Comment by jmarnold** [comment]
Already have this issue logged a few times.

**Comment by jeremydmiller** [comment]
Dupl.icate, my bad.
