### ISSUE TITLE
ripple install with the -p flag doesn't seem to walk the dependency tree 

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/ripple#217]
Did ripple install FubuMVC.StructureMap -p [something] today, and ripple did not also install FubuMVC.Core or StructureMap.

**Comment by jmarnold** [comment]
Could've been a network hiccup maybe. That code absolutely goes through the
dependency walking mechanism. [insert rant here about how our logging needs
to be better]

**Comment by jeremydmiller** [comment]
Worked perfectly a minute later with a different, bigger dep tree.  I'm closing this.
