### ISSUE TITLE
Leverage nuget.core.dll more

### ISSUE THREAD

**Issue by SimonCropp** [FubuMvcArchive/ripple#227]
Since you guys already reference nuget.core.dll why dont you make more use of it?

For example in `FloatingFeed` to get the latest nuget by name you can do an explicit query for it.

```
    public override IRemoteNuget FindLatestByName(string name)
    {
        var repo = PackageRepositoryFactory.Default.CreateRepository(Url);
        var packages = repo.FindPackagesById(name);
        if (_stability == NugetStability.ReleasedOnly)
        {
            packages = packages.Where(x => x.IsAbsoluteLatestVersion);
        }
        else
        {
            packages = packages.Where(x => x.IsLatestVersion);
        }

        var package = packages.FirstOrDefault();
        if (package == null)
        {
            return null;
        }
        var dataServicePackage = (DataServicePackage)package;

        return new RemoteNuget(name, package.Version.ToString(), dataServicePackage.DownloadUrl.AbsoluteUri, this);
    }
```

This way you dont need to stuff around with url concatenation and querying the entire feed using string matches

**Comment by jeremydmiller** [comment]
We're actually trying to go the other way around because Nuget.Core is buggy and stupidly chatty w/ the network round trips;-0  I'd like to completely get away from Nuget.Core's IPackage and IPackageRepository abstractions if we can.

**Comment by SimonCropp** [comment]
@jeremydmiller ahh in that case I fully support moving off nuget core. I thought it was a design decision to use it. 

Less dependencies FTW

Consider this issue gone.
