### ISSUE TITLE
Ripple should run when in a detached head state

### ISSUE THREAD

**Issue by merrickjeff** [FubuMvcArchive/ripple#233]
Should be able to specify a branch in the case where ripple is unable to detect the current branch. Would also be useful if it could assume Master, possibly after warning and giving you a chance to abort.

**Comment by jmarnold** [comment]
Can you give me some use cases here? I'm not sure I'm following you completely

**Comment by merrickjeff** [comment]
git checkout head~6
ripple restore

**Comment by jmarnold** [comment]
Fixed in the 3.0 branch
