### ISSUE TITLE
Build failing - type or Namespace None not found

### ISSUE THREAD

**Issue by mavnn** [FubuMvcArchive/ripple#263]
I'm getting a build error trying to build the 3.0 branch due to a missing type (see below). It looks like `None` is supposed to be a descendent of ProjectItem from FubuCsProj, but I can't get any further than that.

```
Error   7   The type or namespace name 'None' could not be found (are you missing a using directive or an assembly reference?)  <mypath>\ripple\src\ripple\MSBuild\ProjFile.cs  45  16  ripple
```

**Comment by mavnn** [comment]
Looking at FubuCsProj I'm guessing the publicly available git repo is out of date given it has similar classes like `CodeFile` but is missing `None`.

**Comment by jmarnold** [comment]
Got it.
