### ISSUE TITLE
Be nice to have a "ripple restore --force" that just makes things right

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/ripple#33]
It'd be nice to make ripple restore check the versions against the packages model instead of just assuming that what's exploded is right.

Saw this by changing versions in the ripple.config for a locked dependency, then did ripple restore.  Did not upgrade to the designated version.  Ran ripple clean, then ripple restore and it did the trick.

**Comment by jmarnold** [comment]
Only logical thing I could think of for this is to make floated dependencies be corrected when the ForceFlag is applied. See here:
https://github.com/DarthFubuMVC/ripple/blob/master/src/ripple.Testing/Nuget/LocalDependenciesTester.cs#L62
