### ISSUE TITLE
ripple update doesn't update the floats if the packages are already exploded

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/ripple#35]
I'm expecting that ripple update will update any and all of the floats.  I had to do ripple clean then ripple restore to get the new version of a published nuget.

**Comment by jmarnold** [comment]
Isn't this covered here? https://github.com/DarthFubuMVC/ripple/issues/33

**Comment by jmarnold** [comment]
Actually, can you describe the usage you have in mind? With a couple of examples of floats/fixed/mixed?

**Comment by jeremydmiller** [comment]
Sure, what happened was that I was working in Portal, and my local copy was currently 2 versions behind the edge of FubuMVC.SlickGrid.  I did "ripple update" expecting that would fetch the latest of FubuMVC.SlickGrid.  It did not, so I had to do ripple clean, then ripple restore and got exactly what I wanted with the latest version of the FubuMVC.SlickGrid nuget.
