### ISSUE TITLE
Very flakey behavior with FubuMVC.StructureMap

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/ripple#38]
I'm seeing this in the fubu solution.  Run rake once, everything is good.  Run it again, and the restore tries to replace FubuMVC.StructureMap, blows up in the middle, and leaves the unexploded nukpg file in place that has to be cleared out by hand.

Sometimes it whines because of trying to delete a non-empty directory

**Comment by chester89** [comment]
same thing with me, but this happened without any ties to StructureMap project - also in other of my projects where I use ripple for dependency management
