### ISSUE TITLE
Cannot hard code the /buildsupport structure into ripple.exe

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/ripple#39]
We want ripple.exe to be usable as a CLI tool on the PATH.  We'll need to change SolutionFiles accordingly.  The parent.parent() off the buildsupport does not work.

**Comment by jmarnold** [comment]
How about this for a plan:

From the current directory, recursively walk up the filesystem until you find a ripple.config file. The presence of the ripple.config file denotes the root of the repository.

From the root of the repository/solution: the PARENT of that root is what we assume to be the "code" directory.

**Comment by jeremydmiller** [comment]
I agree with that, but you also have to watch how many you go up.  Let's cap the number of "walks" up and say that you can only run ripple from within a folder containing a csproj file, the project directory, or the "code" directory.

I had problems in the early days where it would scan up too far and go super wonkey when it hit c:\

**Comment by jmarnold** [comment]
I'm thinking it'll work roughly the same way that git does if we do a shallow search for ripple.config with each walk. If you make it to the root, then you just bomb out, I think. Of course, this is all theoretical and I have no idea how it'll play out when I actually write it.

I think the shallow search for ripple.config with each walk will be cheaper than deep searching for a csproj file from the current directory.

**Comment by jmarnold** [comment]
Got it 777731e1c3a0865384a37377e9487417553ce8e7
