### ISSUE TITLE
Install a nuget that's already exploded to the solution to a project should not re-explode

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/ripple#41]
Did "ripple install Selenium.WebDriver" to the solution,

then...

ripple install Selenium.WebDriver -p fubu.Testing

Re-fetched and exploded the nuget.  Needs to be smarter here about what does and does not need to be done.

**Comment by jmarnold** [comment]
Got it 043dd68866b9e3209f5af11a4c2ce4c455e79509
