### ISSUE TITLE
ripple upgrade --nuget [foo] --force does not work

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/ripple#47]
Tried it in FubuWorld to upgrade Selenium.WebDriver.  The first try threw the "you must use the --force" flag, and that's fine, but you had to scroll way up to see it.

Tried it a 2nd time and it just didn't do anything.  Threw an exception about having more than one value in a sequence somewhere we're calling Single()

**Comment by jeremydmiller** [comment]
Ok, maybe not.  Worked the 2nd time I tried this.  Dunno.

**Comment by jeremydmiller** [comment]
Take that back, did NOT work on the 2nd try.  Downloaded the new nuget, but didn't replace the old.

**Comment by jmarnold** [comment]
Alright, I think I ran into an issue with this while I was using it in the office. I'll start pushing through it later today.

**Comment by jmarnold** [comment]
Got it 043dd68866b9e3209f5af11a4c2ce4c455e79509
