### ISSUE TITLE
Need to pull the Classic/Not Stupid mode out of the ripple.config file

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/ripple#48]
The read the tea leaves if there's a packages.config assume that it's classic mode is biting me.  This shouldn't happen, but does-->

Say you get a packages.config file that gets bundled into a bottle that gets exploded out.  Ripple thinks it's a classic mode package and hilarity results.

**Comment by jmarnold** [comment]
Hmm, where are you seeing this one? 

ripple.config doesn't store the mode. The classic mode detection _should_ be smart enough to ignore anything within a fubu-content directory. But I'm not brave enough to claim that I have that working perfectly.

**Comment by jmarnold** [comment]
Got this earlier c196e2d2c378b61050426515a5e72323ef86e278
