### ISSUE TITLE
ripple restore needs to "fix" fixed versions

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/ripple#50]
So let's say that we manage to have the wrong version of an exploded nuget, then run ripple restore. The old, exploded nuget is left in place even though it's the wrong version according to our ripple.config.

**Comment by jmarnold** [comment]
So ripple restore --forced for fixing wrong versions in floats, but a ripple restore should _always_ fix fixed versions?

**Comment by jmarnold** [comment]
Got it 043dd68866b9e3209f5af11a4c2ce4c455e79509
