### ISSUE TITLE
Missing '/' character on the private nuget feed in ripple.config.

### ISSUE THREAD

**Issue by andhernand** [FubuMvcArchive/ripple#51]
I created a new fubusln project using fubu.exe. When I ran 'ripple convert' the ripple.config file is updated to the new structure. I then ran 'ripple install FubuMVC.Diagnostics -p PROJECTNAME' I received an unauthorized exception thrown. Upon further checking the private nuget feed is missing the trailing '/' character. When I add the trailing '/' character I no longer recieve the unauthorized exception and diagnostics is installed to my project.

**Comment by jmarnold** [comment]
Was this in the office? I'm wondering if something weird happened with the firewall. I removed the trailing slash but in a new conversion I was getting nasty 404s. 

I haven't been able to reproduce the unauthorized one, though.

**Comment by andhernand** [comment]
I am going to place this on the internal firewall. It doesn't appear to be happening anymore.
