### ISSUE TITLE
Nuget "Groups" that need to be locked together?

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/ripple#65]
We've got two examples that I can think of:

RavenDb -- 3-4 packages, all versioned together, all strong named
WebDriver -- 3-4 packages, same situation.

When you update one, you _always_ have to update the others to the exact same version.

Do something in ripple to introduce a logical nuget "group?"

**Comment by jmarnold** [comment]
This is mostly handled with the "--force" flag on an update operation
(it'll warn you if you're missing it and fail on a subsequent validate).
But I think the groups could operate an implicit force maybe?

**Comment by jeremydmiller** [comment]
I like the implicit force.  A warning is probably good enough, but I updated 3/4 and it didn't warn me about the 4th.

**Comment by jmarnold** [comment]
The groups are going to be more beneficial. The warnings only generate when the current configuration and/or local dependencies don't match the nuspecs. The problem is that most people don't keep up with the nuspecs so the warnings are only as helpful as the specs.
