### ISSUE TITLE
Ripple update is not updating the floats

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/ripple#75]
Saw this this morning with FubuWorld.  Ran ripple update and the floats from the fubu TeamCity feed did not get updated.

**Comment by jeremydmiller** [comment]
Hold on this one.  Looks like the TC for Bottles isn't publishing nugets right now.

**Comment by jmarnold** [comment]
I'll look at this in a while.

On Wed, May 15, 2013 at 10:05 AM, Jeremy D. Miller <notifications@github.com

**Comment by jeremydmiller** [comment]
Nevermind, nothing to see here, move along....
