### ISSUE TITLE
Seeing differences feeds in ripple describe and what and ripple.config

### ISSUE THREAD

**Issue by KevM** [FubuMvcArchive/ripple#83]
I added a feeds element to the ripple config [manually](http://darthfubumvc.github.io/ripple/ripple/gettingstarted/feeds/) as I wasn't sure if there was a command for that. Added a feed to our internal nuget server and removed the Fubu edge feed.

The log produced via ripple describe doesn't match the feeds in ripple.config. It seems that the default feeds are getting restored internally and the one I added is not considered.

**Ripple.config**

``` xml
<?xml version="1.0"?>
<ripple xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Name>dovetail-thingy</Name>
  <NugetSpecFolder>packaging/nuget</NugetSpecFolder>
  <SourceFolder>source</SourceFolder>
  <BuildCommand>rake</BuildCommand>
  <FastBuildCommand>rake compile</FastBuildCommand>
  <DefaultFloatConstraint>Current</DefaultFloatConstraint>
  <DefaultFixedConstraint>Current,NextMajor</DefaultFixedConstraint>
  <Feeds>
    <Feed Url="http://internal.company./com/nuget/" Mode="Fixed" Stability="ReleasedOnly" />
    <Feed Url="http://nuget.org/api/v2" Mode="Fixed" Stability="ReleasedOnly" />
  </Feeds>
  <Nugets>
    <Dependency Name="Dovetail.SDK" Version="3.2.10.8" Mode="Fixed" />
    <Dependency Name="Dovetail.SDK.Bootstrap" Version="0.4.157" Mode="Fixed" />
    <Dependency Name="log4net" Version="2.0.0" Mode="Fixed" />
    <Dependency Name="structuremap" Version="2.6.4.1" Mode="Fixed" />
  </Nugets>
  <Groups />
  <Nuspecs />
</ripple>
```

**Ripple.log**

```
5/21/2013 5:11:55 PM: [Info] Classic Mode Detected
5/21/2013 5:11:55 PM: [Debug] 
=================================================================================================================================================================================
Solution "dovetail-thingy": c:\projects\dovetail-thingy\ripple.config
=================================================================================================================================================================================
     ** Solution-Level
        * Dovetail.SDK               3.2.10.8
        * Dovetail.SDK.Bootstrap     0.4.157 
        * log4net                    2.0.0   
        * structuremap               2.6.4.1 
     ** NuGet Feeds
        * Feed     http://build.fubu-project.org/guestAuth/app/nuget/v1/FeedService.svc (Float)
        * Feed     http://nuget.org/api/v2 (Fixed)                                             
        * Feed     http://packages.nuget.org/v1/FeedService.svc (Fixed)                        
     ** Projects
        * Project "Dovetail.Thingy"     c:\projects\dovetail-thingy\source\Dovetail.Thingy\Dovetail.Thingy.csproj
             ** Dependencies
                * Dovetail.SDK               Float
                * Dovetail.SDK.Bootstrap     Float
                * log4net                    Float
                * structuremap               Float
     ** Missing
        * Dovetail.SDK               3.2.10.8
        * Dovetail.SDK.Bootstrap     0.4.157 
        * log4net                    2.0.0   
        * structuremap               2.6.4.1 
```

**Comment by jmarnold** [comment]
@KevM I think the core problem is that ripple is detecting "classic mode" here. During class mode, ripple uses defaults for the things that classic mode just doesn't provide (e.g., feeds).

A couple of questions:
1. What version of ripple are you using? Is this from the ripple-cli gem?
2. Is your solution still using the old ripple? Have you done a ripple convert?

Classic mode is detected by the absence of ripple.dependencies.config files (I originally tried doing this by detecting the presence of a package.config file but that proved to be problematic). Maybe that's the problem?

**Comment by KevM** [comment]
I just did a gem install ripple-cli and the ripple init and edited the config to match my project settings like source vs src and manually added the feeds. I know nothing no prior ripple in effect. I am a fresh user and it feels painful so far. :frown:

**Comment by jmarnold** [comment]
So the getting started story needs work, right? I think the init command
definitely needs some love.

**Comment by jmarnold** [comment]
@KevM This just hit master and the docs, but the new init command simply creates the appropriate ripple.config and corresponding ripple.dependencies.config files. I've tested it out locally on a few different solutions. The basic usage looks like:
1. ripple init MySolution
2. ripple install FubuCore -p MyProject

Let me know if this helps what you were seeing.

http://darthfubumvc.github.io/ripple/ripple/commands/init/

**Comment by KevM** [comment]
1. cloned master of Ripple
2. rake
3. rake gem:install
4. cd to my project directory
5. whack all the existing ripple files
6. ripple init -f my feed-url the-solution-name

```
ripple: Cannot initialize existing solution
```

Looking at the code this seems to mean that I cannot a directory that has a solution present in the source directory.

**Comment by jmarnold** [comment]
That message just means that you can't have an existing ripple.config. In
ripple terms, you can't be in a "ripple" directory. The ripple.config file
is to a ripple directory as the .git directory is to a git repository, if
that helps.

Did you still have a config file lying around?

**Comment by KevM** [comment]
I was even getting this problem in empty directories. Looks like somehow I got a ripple.config in my project directory.  _c:\projects_ Removing that file got ripple init working again. So ripple walks up directories looking for ripple.configs? They are hierarchical?

**Comment by jmarnold** [comment]
Yeah, I modeled it after the git mechanics. That way you can do ripple
operations anywhere in your ripple directory and it would remain relative
to the parent. For example, if you were in a project directory instead of
the root, you could still do: ripple install FubuCore -p MyProject

**Comment by KevM** [comment]
Maybe a better error would be 

_ripple: Cannot initialize an existing rippleized project. I found a ripple.config at {path}_

**Comment by jmarnold** [comment]
Good call. I think adding some more docs for the ripple directory structure
could probably help here as well.

**Comment by KevM** [comment]
I have a PR almost ready but test are failing in teardown unrelated to my changes something to do with test file/directory deletion.

**Comment by KevM** [comment]
Added PR #88 to add the error context I griped about.
