### ISSUE TITLE
Ripple Convert does not honor ripple.config Feeds

### ISSUE THREAD

**Issue by KevM** [FubuMvcArchive/ripple#96]
While converting a project I have noticed that `ripple convert` does not honor the Feeds I put into the ripple config.
- ripple init
- update ripple.config to have our project defaults and source feeds.
- ripple convert 

The local server's nuget packages are not found. The ripple config Feeds elements now contain the default feeds.

``` xml
<Feeds>
    <Feed Url="http://build.fubu-project.org/guestAuth/app/nuget/v1/FeedService.svc" Mode="Float" Stability="ReleasedOnly" />
    <Feed Url="http://nuget.org/api/v2" Mode="Fixed" Stability="ReleasedOnly" />
  </Feeds>
```

To work around I had to re-edit the _ripple.config_ feeds and do a `ripple update`

**Comment by jmarnold** [comment]
This is related to the convert issue I added earlier today. Today ripple
convert just converts old ripple solutions (not nuget). We'll make it
smarter.
