### ISSUE TITLE
Ripple feeds can be file based but do not support relative paths

### ISSUE THREAD

**Issue by KevM** [FubuMvcArchive/ripple#98]
The [docs](http://darthfubumvc.github.io/ripple/ripple/gettingstarted/concepts/) show that file based feeds are possible. It does not appear that file based feeds relative to the  _ripple.config_ are supported.

This is supported by Nuget. Scenario where this can be handy: You want a (private) repo to have a little built in nuget source and you don't want to force users to manually update the ripple.config with the full path.

**Comment by KevM** [comment]
I'll be working on this tomorrow. Please let me know if there are any objections to adding support for this.

**Comment by jmarnold** [comment]
Not at all.

**Comment by jmarnold** [comment]
This _should_ just be a simple change in the FeedProvider class.

**Comment by jmarnold** [comment]
Closed via e7d1d5b84c3a6b6335b29670cf0929c2bb8d75f3
